### ISSUE TITLE
Reflectivity is fixed (=100) regardless of material. 

### ISSUE THREAD

**Issue by hmorita2020** [lvfengchi/livox_laser_simulation#12]
intensity "= rayShape->GetRetro(pair.first);" is always returned 0, and Reflectivity is assigned 100.
 pt.reflectivity = 100;
It would be very helpful to get intensity that changes with the material, is there any fix for that?

**Comment by EpsAvlc** [comment]
Does gazebo support providing different reflectivity w.r.t materials? I used to try it but in my memory, gazebo doe not support this feature.(All reflectivity equals.)
If you have idea about it, please notify me.

**Comment by hmorita2020** [comment]
Thank you for your response.  
checked the source code and unfortunately it is not supported... 
I’ll consider the method.

>https://github.com/gazebosim/gz-sensors/blob/ign-sensors6/src/Lidar.cc
double Lidar::Retro(const int /*_index*/) const
{
  return 0.0;
}
