### ISSUE TITLE
The range measurement is not accurate?

### ISSUE THREAD

**Issue by chenfeiyi** [lvfengchi/livox_laser_simulation#13]
Thank you for your sharing. 
I'm trying use your simulation to generate some data to verify my algorithm on the extrinsic calibration of calibrate camera and livox. A problem show up when I put a unit box in front the Livox. The unit box is 1m*1m*1m set in gazebo. The measurement from point cloud tells me that the box is about 0.9m wide. I'm confused with this result. Do you know any idea?
Looking forward to your response.

**Comment by chenfeiyi** [comment]
This result is test on ubuntu18 melodic, gazebo9.  The range measure is correct when I tested on another pc using ubuntu16, gazebo7

> Thank you for your sharing. I'm trying use your simulation to generate some data to verify my algorithm on the extrinsic calibration of calibrate camera and livox. A problem show up when I put a unit box in front the Livox. The unit box is 1m_1m_1m set in gazebo. The measurement from point cloud tells me that the box is about 0.9m wide. I'm confused with this result. Do you know any idea? Looking forward to your response.

**Comment by EpsAvlc** [comment]
Sorry for my late reply. May you try the latest commit?  I have fixed this problem.

**Comment by chenfeiyi** [comment]
Thank you! The range measurements are correct now.
