### ISSUE TITLE
The published message is in pointcloud2 format, whether the scan line information can be obtained.

### ISSUE THREAD

**Issue by feiyang-he** [lvfengchi/livox_laser_simulation#6]
The livox sdk provides a lidar point cloud in CustomMsg format, which contains the 'line' field. Using this 'line' field can easily process point cloud data, and whether similar information can be obtained in this project.

Or is it possible to get the order of the point cloud in the ros message?

**Comment by EpsAvlc** [comment]
I notice this too. Can you explain the line field of Livox Lidar? Or can you just plot the point cloud of each line? It will help me understand it and try to implement this characteristic.

**Comment by feiyang-he** [comment]
> I notice this too. Can you explain the line field of Livox Lidar? Or can you just plot the point cloud of each line? It will help me understand it and try to implement this characteristic.

https://blog.csdn.net/brightming/article/details/117533010
I think this blog can explain the characteristics of the line

**Comment by EpsAvlc** [comment]
> > I notice this too. Can you explain the line field of Livox Lidar? Or can you just plot the point cloud of each line? It will help me understand it and try to implement this characteristic.
> 
> https://blog.csdn.net/brightming/article/details/117533010
> I think this blog can explain the characteristics of the line

I see. I will try to do it.

**Comment by EpsAvlc** [comment]
I just made it in the main branch. See the newest commit.
