### ISSUE TITLE
Mismatch between point cloud and urdf model

### ISSUE THREAD

**Issue by igricart** [lvfengchi/livox_laser_simulation#7]
When using the `Gazebo 9` version, my point cloud doesn't match with my Robot Model when shown in RViz, is that something that also happens in Gazebo 7? And is there any fix for that?

**Comment by EpsAvlc** [comment]
Could you explain it more clearly? Or may you give a screenshot?

**Comment by Carlita96** [comment]
Hello again,

I have uploaded the branch [misaligment-issue-gazebo-9](https://github.com/Carlita96/livox_laser_simulation/tree/misaligment-issue-gazebo-9) in a fork from this repository to show the state of the code we are working with. The test can be run with the launch file: [run_target_test_simulation.launch](https://github.com/Carlita96/livox_laser_simulation/blob/misaligment-issue-gazebo-9/launch/run_target_test_simulation.launch).

Is this of any help?

**Comment by EpsAvlc** [comment]
May you provide this model? I can't open gazebo because I don't have it.

```
		<include>
			<uri>model://calibrate_lidars/urdf/calibration_target</uri>
			<pose>5 1.5 0.75 0 0 0.2</pose>
		</include>
```

**Comment by EpsAvlc** [comment]
Sorry for the late reply.

I recently fix a bug which lead to inaccurate point range in(#13) . May you try the latest commit ?
