### ISSUE TITLE
Which PCL version is required? Cant catkin make

### ISSUE THREAD

**Issue by protoCAD** [lvfengchi/livox_laser_simulation#8]
Hello,

i tried to catkin_make this but getting alot of errors from pcl For example:

/usr/include/pcl-1.10/pcl/point_types.h:627:1: error: ‘plusscalar’ is not a member of ‘pcl::traits’
  627 | POINT_CLOUD_REGISTER_POINT_STRUCT (pcl::BRISKSignature512,

Am i using the wrong version of pcl?

**Comment by EpsAvlc** [comment]
PCL 1.7 and 1.8 were tested.
